remote_theme: "owasp/www--site-theme@main"

#override default star and watch buttons
code_user: zaproxy
code_repo: zaproxy

# core files/folders to exclude
exclude:
 - README.md

plugins:
 - jekyll-include-cache-0.2.0